<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>meml</string>
   </array>
  <key>name</key>
  <string>meml</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.meml</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(import|from|export)</string>
          <key>name</key>
          <string>keyword.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(component)</string>
          <key>name</key>
          <string>punctuation.definition.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?&lt;=\(\s*)\w*(?=.*))</string>
          <key>name</key>
          <string>entity.name.tag.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?&lt;=\(component\ )\w*)</string>
          <key>name</key>
          <string>variable.other.constant.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?&lt;=\()\w*(, \w*)*(?=\)))</string>
          <key>name</key>
          <string>variable.other.constant.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+|-|(?&lt;!/)(/)(?!/)|\*|=)</string>
          <key>name</key>
          <string>punctuation.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\(|\))</string>
          <key>name</key>
          <string>punctuation.definition.tag.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\w*)(?==))</string>
          <key>name</key>
          <string>variable.meml</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.meml</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.meml</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.meml</string>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.meml</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.meml</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.meml</string>
          <key>end</key>
          <string>(&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.meml</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
